### ISSUE TITLE
Numerical instability with negative ell

### ISSUE THREAD

**Issue by mikeroswell** [mikeroswell/MeanRarity#6]
`rarity(c(10,1),-1e4)` returns `Inf`, should be about 1.1

**Comment by mikeroswell** [comment]
check out `Rmpfr` [https://cran.r-project.org/web/packages/Rmpfr/index.html](https://cran.r-project.org/web/packages/Rmpfr/index.html)

**Comment by dushoff** [comment]
Have you looked at how other Hill-calculating packages handle this?

**Comment by mikeroswell** [comment]
Good question. `vegan` fails sooner with low ell: `vegan::renyi(c(10,1), scales =7818, hill=T)`;  returns `Inf` but `MeanRarity::rarity(c(10,1), q= 7818)` works, but is better with high ell, where `q=-296` fails for `MeanRarity::rarity` but not `vegan::renyi`. Need to explore implementation (guessing use of logs and exponents).

**Comment by mikeroswell** [comment]
`hillR` seems to have similar implementation to `vegan`

**Comment by mikeroswell** [comment]
resolved by adding a warning.
